[package]
name = "zns-keys"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "zns-keys"
path = "src/main.rs"

[dependencies]
rand_core = "0.10.1"
bech32 = "0.12.0"
blake2b_simd = "1.0.4"
sev = { version = "8.0.0", default-features = false, features = ["snp"] }
chacha20poly1305 = { version = "0.11.0", features = ["zeroize"] }
zeroize = "1.9.0"
