[network]
network = "Testnet"
listen_addr = "[::]:18233"

[state]
cache_dir = "/var/lib/zebra"
ephemeral = false

[rpc]
listen_addr = "127.0.0.1:18232"
enable_cookie_auth = false
parallel_cpu_threads = 0

[health]
listen_addr = "127.0.0.1:8080"
min_connected_peers = 1
ready_max_blocks_behind = 2
ready_max_tip_age = "5m"
enforce_on_test_networks = true

[tracing]
use_color = false
force_use_color = false
